package interfaces;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import servicefacture.FactureRemote;

public class LoginController {
	@FXML
	private ImageView logo;
	@FXML
	private ImageView malek;
	@FXML
	private ImageView sinda;
	@FXML
	private ImageView ouiem;
	@FXML
	private ImageView mootaz;
	@FXML
	private ImageView ahmed;
	@FXML
	private ImageView mtimet;
	@FXML
	private Label nomOp;
	@FXML
	private Label id;

	// Event Listener on ImageView[#malek].onMouseClicked
	@FXML
	public void redirectionMalek(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#sinda].onMouseClicked
	@FXML
	public void redirectionSinda(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#ouiem].onMouseClicked
	@FXML
	public void redirectionOuiem(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#mootaz].onMouseClicked
	@FXML
	public void redirectionMootaz(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#ahmed].onMouseClicked
	@FXML
	public void redirectionAhmed(MouseEvent event) throws IOException, NamingException {
		// TODO Autogenerated
		int idop= Integer.parseInt(id.getText());
		FXMLLoader loader = new FXMLLoader(getClass().getResource("Bills.fxml"));
		Parent root=loader.load();
		BillsController display=loader.getController();
		//display.setclient(c.getId());
		
		//System.out.println(c.getIdoperator());

		 BillsController controller = 
		loader.<BillsController>getController();
		controller.logo(this,idop);
		System.out.println("id login: "+idop);
		 
		   ahmed.getScene().setRoot(root);

	}
	// Event Listener on ImageView[#mtimet].onMouseClicked
	@FXML
	public void redirectionMtimet(MouseEvent event) {
		// TODO Autogenerated
	}
	public void logo(HomeController t, int i) throws FileNotFoundException, NamingException {
		
		//------------------context-----------------------
				Context context;
				
				context = new InitialContext();
				String j2 = "/CRM-ear/CRM-ejb/Facture!servicefacture.FactureRemote";
				FactureRemote dao= (FactureRemote) context.lookup(j2);
				//---------------login--------------------
			
			dao.findOperatorbyid(i);
			nomOp.setText(dao.findOperatorbyid(i).getName());
			id.setText(String.valueOf(dao.findOperatorbyid(i).getIdoperator()));
			FileInputStream input = new FileInputStream(dao.findOperatorbyid(i).getImage());
			Image img = new Image(input);
			logo.setImage(img);
	
	}

}
